---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.git

- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for installation in {{ kpt_bin_exe }}
  become: true
  stat:
    path: '{{ kpt_bin_exe }}'
  changed_when: false
  register: kpt_binary
- when: not kpt_binary.stat.exists
  block:
    - name: downloading {{ kpt_url }} to {{ kpt_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ kpt_url }}'
        dest: '{{ kpt_tmp_archive }}'
        checksum: '{{ kpt_checksum }}'
        mode: 0644
    - name: mkdir {{ kpt_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ kpt_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ kpt_tmp_archive }} into {{ kpt_install_dir }}
      become: true
      become_user: root
      unarchive:
        src: '{{ kpt_tmp_archive }}'
        dest: '{{ kpt_install_dir }}'
        creates: '{{ kpt_bin_exe }}'
        remote_src: true
  always:
    - name: rm -f {{ kpt_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ kpt_tmp_archive }}'
        state: absent
- name: link {{ kpt_link_exe }} to {{ kpt_bin_exe }}
  become: true
  become_user: root
  file:
    src: '{{ kpt_bin_exe }}'
    dest: '{{ kpt_link_exe }}'
    state: link
